settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: nextcloud
    name: Nextcloud
    description: 'Personal, local deployment of Nextcloud.'
    url: 'https://cloud.server.rip'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: server.rip
    name: Server.RIP
    description: 'Portal for making requests on Plex.'
    url: 'https://server.rip'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: tautulli
    name: Tautulli
    description: 'Analytics and monitoring for Plex.'
    url: 'https://tautulli.server.rip'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true

  - id: odoo
    name: Odoo
    description: 'ERP software for personal business'
    url: 'https://invoice.copycomma.com'
    method: GET
    expectStatus: 200
    followRedirect: true
    linkable: true
